# Generated by Django 2.2.6 on 2019-10-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('responsabilities', models.TextField(verbose_name='Responsabilities')),
                ('minimun_requirements', models.TextField(verbose_name='Minimun Requirements')),
                ('preferred_requirements', models.TextField(blank=True, verbose_name='Preferred Requirements')),
                ('type', models.CharField(max_length=80, verbose_name='Type')),
                ('compensation', models.FloatField(blank=True, verbose_name='Compensation')),
                ('duration', models.IntegerField(blank=True, verbose_name='Duration')),
                ('duration_unit', models.CharField(blank=True, max_length=20, verbose_name='Duration Unit')),
                ('company', models.CharField(max_length=120, verbose_name='Company')),
                ('department', models.CharField(max_length=120, verbose_name='Department')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('state', models.CharField(max_length=120, verbose_name='State')),
                ('country', models.CharField(max_length=120, verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'JobOffers',
            },
        ),
    ]
