# Generated by Django 2.2.6 on 2019-10-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOfferProjectsDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='Distance')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.JobOffer')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserProjects')),
            ],
            options={
                'verbose_name_plural': 'JobOfferProjectsDistances',
            },
        ),
    ]
