# Generated by Django 2.2.6 on 2019-10-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jobofferprojectsdistance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobofferdistance',
            unique_together={('user', 'job_offer')},
        ),
        migrations.AlterUniqueTogether(
            name='jobofferexperiencedistance',
            unique_together={('experience', 'job_offer')},
        ),
        migrations.AlterUniqueTogether(
            name='jobofferprojectsdistance',
            unique_together={('projects', 'job_offer')},
        ),
        migrations.AlterUniqueTogether(
            name='jobofferskilldistance',
            unique_together={('skill', 'job_offer')},
        ),
    ]
